language: cpp
sudo: false
compiler:
  - clang
  - gcc
platform:
  - x86
  - x64
os:
  - linux
  - osx
before_script:
  - mkdir build
  - cd build
  - cmake -DGeant4_DIR=/pathToGeant4Instalation/lib/Geant ..
script:
  - make && make install
notifications:
  email:
    - hector.alvarez@usc.es
